openapi: '3.0.2'
info:
  title: AI Cockpit Decisions
  version: '0.0.1'
  description: |
    This API is part of project AI cockpit. 

    For more details see: TODO

servers:
  - url: http://localhost:8080/v0

paths:
  /info:
    get:
      description: shall deliver info on interface version and hosting system, readonly
      operationId: getInfo
      responses:
        '200':
          description: base info 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Info'
  /decisions:
    get:
      description: get all decisions in this system
      operationId: getAllDecisions
      responses:
        '200':
          description: list all decisions in this system
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Decision'
    post:
        description: create a decisions config in this system
        operationId: createDecision
        requestBody:
          description: Decision test to be created
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Decision'
        responses:
          '200':
            description: create new decision
  /decision/{id}:
    put:
        description: update a Decision
        operationId: updateDecision
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: true
            description: Numeric ID of decision to be updated        
        requestBody:
          description: Decision to be updated
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Decision'
        responses:
          '200':
            description: update a decision 

components:
  schemas:
    Info:
      type: object
      properties:
        generation-date:
          type: string
          format: date-time
        systemDescription:
          type: string
        apiVersion:
          type: string
    Decision:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        uuid:
          type: string
          format: uuid
          description: Globally unique ID
        autonomyLevel:
          $ref: '#/components/schemas/AutonomyLevel'
        followingDecisions:
          type: array
          description: "Decisions that use output of this decisions. Can be null"
          items:
            $ref: '#/components/schemas/Decision'
          example:
            - id: 0
              name: NextDecision
              uuid: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
              autonomyLevel: autonomous
            - id: 1
              name: AnotherDecision
              uuid: "3fa85f64-4417-4562-b3fc-2c963f66afa6"
              autonomyLevel: proposalOnly
    AutonomyLevel:
      type: string 
      enum:
        - autonomous
        - proposalOnly
        - disabled