openapi: '3.0.2'
info:
  title: AI Cockpit Decisions
  version: '0.0.1'
  description: |
    This API is part of project AI cockpit. 

    For more details see: TODO

servers:
  - url: http://localhost:8080/v0

paths:
  /info:
    get:
      description: shall deliver info on interface version and hosting system, readonly
      operationId: getInfo
      responses:
        '200':
          description: base info 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'datatypes.yaml#/components/schemas/Info'
  /decision:
    get:
      description: get all decisions in this system
      operationId: getAllDecisions
      responses:
        '200':
          description: list all decisions in this system
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'datatypes.yaml#/components/schemas/Decision'
    post:
        description: create a decisions config in this system
        operationId: createDecision
        requestBody:
          description: Decision test to be created
          required: true
          content:
            application/json:
              schema:
                $ref: 'datatypes.yaml#/components/schemas/Decision'
        responses:
          '200':
            description: create new decision
  /decision/{id}:
    get:
      description: get decisions by id 
      operationId: getDecisionsById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of decision to load
      responses:
        '200':
          description: returns decisions by id
          content:
            application/json:
              schema:
                items:
                  $ref: 'datatypes.yaml#/components/schemas/Decision'
        '404':
          description: A decision with the specified ID was not found.
    put:
        description: update a Decision
        operationId: updateDecision
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: true
            description: Numeric ID of decision to be updated        
        requestBody:
          description: Decision to be updated
          required: true
          content:
            application/json:
              schema:
                $ref: 'datatypes.yaml#/components/schemas/Decision'
        responses:
          '200':
            description: update a decision
          '404':
            description: A decision with the specified ID was not found.
