components:
  schemas:
    ActionType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        endpoint:
          type: string      
        executionPolicy:
          type: string
          enum:
          - MANUAL
          - WITHCHECK
          - AUTOMATIC
        module:
          $ref: '#/components/schemas/Module'      
        actions:
          uniqueItems: true
          type: array
          items:
            $ref: 'datatypes.yaml#/components/schemas/Action'
        decisionTypes:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/DecisionType'
    DecisionType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        module:
          $ref: '#/components/schemas/Module'
        decisions:
          uniqueItems: true
          type: array
          items:
            $ref: 'datatypes.yaml#/components/schemas/Decision'
        actionTypes:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ActionType'
    Module:
      type: object
      properties:
        id:
          type: integer
          format: int64      
        name:
          type: string
        description:
          type: string
        useAI:
          type: boolean
        decisions:
          uniqueItems: true
          type: array
          items:
            $ref: 'datatypes.yaml#/components/schemas/Decision'
        actionTypes:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ActionType'
        decisionTypes:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/DecisionType'
        modelType:
          $ref: '#/components/schemas/ModelType'
        sBOMLocation:
          type: object
          additionalProperties:
            type: string
            properties:    
              url:
                type: string
        successors:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Module'
    ModelType:
      type: string 
      enum:
        - LLM
        - ComputerVision
        - RuleBased
        - Misc
    # Model:
    #   type: object
    #   properties:
    #     name:
    #       type: string
    #     version: 
    #       type: string
    #     lastDeployment:
    #       type: string
    #       format: date-time
    #     modelType:
    #       $ref: '#/components/schemas/ModelType'
    #     modelLink:
    #       description: Link to model documentation
    #       type: string
    #       format: uri
    #     publicTrainingData:
    #       description: Is model based on public training data?
    #       type: boolean
    #     linkToPublicTrainingData:
    #       description: Link to public training data / documentation.
    #       type: string
    #       format: uri
