openapi: 3.0.1
info:
  title: AI Cockpit Decisions
  version: '0.0.3'
  description: |
    This API is part of project AI cockpit. 

    For more details see: TODO
servers:
- url: http://localhost:8081/v0

paths:
  /info:
    get:
      description: shall deliver info on interface version and hosting system, readonly
      operationId: getInfo
      responses:
        '200':
          description: base info 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'configurationtypes.yaml#/components/schemas/Info'
  /api/decision:
    get:
      summary: Get all decisions
      operationId: getAllDecisions
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: 'datatypes.yaml#/components/schemas/Decision'
    post:
      summary: Create decision
      operationId: createDecision
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'datatypes.yaml#/components/schemas/Decision'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: 'datatypes.yaml#/components/schemas/Decision'
  /api/action:
    get:
      summary: Get all actions
      operationId: getAllActions
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: 'datatypes.yaml#/components/schemas/Action'
    post:
      summary: Create action
      operationId: save_3
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'datatypes.yaml#/components/schemas/Action'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: 'datatypes.yaml#/components/schemas/Action'
  /api/decision/{id}:
    get:
      summary: Get decisions by id
      operationId: getDecisionsById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: 'datatypes.yaml#/components/schemas/Decision'
  /api/action/{id}:
    get:
      summary: Get action by id
      operationId: getActionsById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: 'datatypes.yaml#/components/schemas/Action'
