# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- generate-compile-code
- test
- verify

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  REPO_BASE: $CI_BUILDS_DIR/ki-cockpit/ai-cockpit-api

cache:
  paths:
    - .m2/repository

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

# TODO
# generate openAPI code
# compile generated code
# unit test result

generate-api-code:
  stage: generate-compile-code
  image: maven:latest
  cache:
    paths:
      - $REPO_BASE/api/decision/generators/
      - $REPO_BASE/api/transparency/generators/
  script:
    - cd $REPO_BASE/api/decision/generators/java-client
    - mvn package
    - cd $REPO_BASE/api/decision/generators/java-client/target/generated-sources/openapi
    - mvn package
    - cd $REPO_BASE/api/decision/generators/java-server
    - mvn package
    - cd $REPO_BASE/api/decision/generators/java-server/target/generated-sources/openapi
    - mvn package    
    - cd $REPO_BASE/api/transparency/generators/java-client
    - cd $REPO_BASE/api/transparency/generators/java-client/target/generated-sources/openapi
    - mvn package    
    - mvn package
    - cd $REPO_BASE/api/transparency/generators/java-server
    - mvn package
    - cd $REPO_BASE/api/transparency/generators/java-server/target/generated-sources/openapi
    - mvn package
