components:
  schemas:
    Info: #Base info on version of interface
      type: object
      properties:
        generation-date:
          type: string
          format: date-time
        systemDescription:
          type: string
        apiVersion:
          type: string  
    ActionType: 
      description: "A type of action that a system can execute"
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        endpoint:
          type: string      
        executionPolicy:
          type: string
          enum:
          - MANUAL
          - WITHCHECK
          - AUTOMATIC  
    Action: 
      description: "An actual action that a system executes"
      type: object
      properties:
        id:
          type: integer
          format: int64
        creationTime:
          type: string
          format: date-time
        name:
          type: string
        description:
          type: string
        actionType:
          $ref: '#/components/schemas/ActionType'
        metadata:
          type: string            
    DecisionType: 
      description: "A type of decision that a system can derive"
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        module:
          $ref: '#/components/schemas/Module'
    Decision: 
      description: "An actual decision that a system made"
      type: object
      properties:
        id:
          type: integer
          format: int64
        acquisitionTime:
          description: Timestamp when the decision was made
          type: string
          format: date-time
        mediaUrl:
          description: Media the decision was based on
          type: string
        actionVisualizationUrl:
          description: Media the decision was based on
          type: string        
        cameraLatitude:
          type: number
        cameraLongitude:
          type: number
        state:
          type: string
          enum:
          - NEW
          - ACCEPTED
          - REJECTED
        description:
          type: string
        module:
          $ref: '#/components/schemas/Module'
        decisionType:
          $ref: '#/components/schemas/DecisionType'
        actions:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Action'            
    Module:
      type: object
      properties:
        id:
          type: integer
          format: int64      
        version:
          type: string
        name:
          type: string
        description:
          type: string
        useAI:
          type: boolean
        model:
          description: "If module uses AI this holds info about model used by module"
          $ref: '#/components/schemas/AIModel'
        actionTypes:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ActionType'
        decisionTypes:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/DecisionType'
        sBOMLocation:
          type: object
          additionalProperties:
            type: object
            properties:    
              url:
                type: string
        successors:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Module'
        submodules:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Module'
    AIModel:
      type: object
      properties:
        name:
          type: string
        version: 
          type: string
        lastDeployment:
          type: string
          format: date-time
        modelType:
          $ref: '#/components/schemas/AIModelType'
        modelLink:
          description: Link to model documentation
          type: string
          format: uri
        publicTrainingData:
          description: Is model based on public training data?
          type: boolean
        linkToPublicTrainingData:
          description: Link to public training data / documentation.
          type: string
          format: uri
    AIModelType:
      type: string 
      enum:
        - LLM
        - ComputerVision
        - RuleBased
        - Misc
