name: Generate code and build

on:
  workflow_dispatch:

jobs:
  build:
    name: "generate code from openapi definition"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    

    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 21
    
        - name: Set up Maven
          uses: stCarolas/setup-maven@v4.5
          with:
            maven-version: 3.9.2

        - name: Generate and build java model lib
          run: |
            cd ${{ github.workspace }}/aicockpit-api/class_libs/java
            ./generate.sh generate
            cd aicockpit-api
            mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}