name: Generate code and build

on:
  workflow_dispatch:

jobs:
  build:
    name: "generate code from openapi definition"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    

    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 21
    
        - name: Set up Maven
          uses: stCarolas/setup-maven@v4.5
          with:
            maven-version: 3.9.2

        - name: Generate and build transparency lib
          run: |
            cd ${{ github.workspace }}/api/transparency/generators/java-lib
            ./generate.sh generate
            cd aicockpit-transparency-jar
            mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Generate and build decision lib
          run: |
              cd ${{ github.workspace }}/api/decision/generators/java-lib
              mvn clean -B package --file pom.xml
              cd target/generated-sources/openapi
              mvn --batch-mode deploy
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Generate client/server code
          run: |
            cd ${{ github.workspace }}/api/decision/generators/java-client
            mvn package
            cd ${{ github.workspace }}/api/decision/generators/java-client/target/generated-sources/openapi
            mvn package
            cd ${{ github.workspace }}/api/decision/generators/java-server
            mvn package
            cd ${{ github.workspace }}/api/decision/generators/java-server/target/generated-sources/openapi
            mvn package    
            cd ${{ github.workspace }}/api/transparency/generators/java-client
            mvn package    
            cd ${{ github.workspace }}/api/transparency/generators/java-client/target/generated-sources/openapi
            mvn package
            cd ${{ github.workspace }}/api/transparency/generators/java-server
            mvn package
            cd ${{ github.workspace }}/api/transparency/generators/java-server/target/generated-sources/openapi
            mvn package